# Generated by Django 3.0.6 on 2020-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
